### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by iamashank** [sonudoo/proxy-server#1]
> http://ps/http://www.imdb.com/

A search query for "godless" on the above link redirects to : 

> http://ps/find?ref_=nv_sr_fn&q=godless&s=all

which results in an invalid request.

It should redirect to : http://ps/http://www.imdb.com/find?ref_=nv_sr_fn&q=godless&s=all

**Comment by sonudoo** [comment]
This issue has been resolved. Please check for the same.
